# .github/workflows/deploy.yaml

name: build-and-deploy

on:
  push:
    branches: [ main ]  # main 分支有 commit 时自动触发该 workflow

jobs:
  build-and-deploy:  # 随便起个名字
    # 配置运行该 workflow 的系统
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '16'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 配置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      # 安装依赖
      - name: Install dependencies
        run: yarn --frozen-lockfile

      # 打包并生成静态文件
      - name: Build site
        run: yarn docs:build

      # # 推送静态文件到 gh-pages 分支
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: docs/.vuepress/dist  # 静态文件生成目录
      #     cname: yichen.ink  # 你网站的域名
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: '-rltgoDzvO --delete'
            SOURCE: dist # 这是要复制到阿里云静态服务器的文件夹名称
            REMOTE_HOST: '49.232.206.238' # 你的阿里云公网地址
            REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
            TARGET: /usr/local/webapp # 打包后的 dist 文件夹将放在 /root/node-server